# Minimum and maximum range of random teleport (in block units)
min-x: -2000
max-x: 2000
min-z: -2000
max-z: 2000

# Queue config
queue-wait-ticks: 20

# Queue BossBar config
queue-bossBar:
  update-ticks: 20
  format: "&6&lIn Queue ({pos}/{all})"
  color: YELLOW

# Message config
messages:
  already-in-queue: "&cAlready in queue"
  player-joined-queue: "&eJoined queue"
  player-cancelled-queue: "&eCancelled queue"
  player-not-in-queue: "&cNot in queue"
  no-permission: "&cNo permission"
  only-player-command: "&cOnly players should execute this command!"
  command-rtp-usage: "&cUsage: /{label} "